runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_SHEET_KEY: "1g2VBvM0zvDYcDMuZE98jfQEkyNxL7UImwAzrEijFGRU"
  CREDENTIALS_FILE: "credentials.json"
  
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static/

- url: /
  script: auto